This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./ReportMain.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file ReportMain.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (9 comparisons).
Generating output file ReportMain.acr....done (9 lines written, 0 warnings).
Output written in ReportMain.acr.
Transcript written in ReportMain.alg.
